-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args: [--no-markdown-linebreak-ext]
        exclude: ^static/(csslibs/|jslibs/|bundle-)
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.4
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: local
    hooks:
    -   id: gen_statics_bundles
        name: gen_statics_bundles
        language: system
        entry: ./gen_statics_bundles.py
        files: ^static/(main.css$|js/)
    -   id: eslint
        name: eslint
        language: system
        entry: sh -c 'type eslint && type node && type npm && eslint static/js/*.js'
        files: ^static/js/
    -   id: stylelint
        name: stylelint
        language: system
        entry: sh -c 'stylelint static/main.css'
        files: ^static/js/main.css$
